title: Progetto
options:
  navigation:
    status: listed
    template: project

tabs:
  home:
    label: Progetto nella Home
    icon: home
    sections:
      colorPicker:
        type: fields
        fields:
          color:
            width: 1/4
            label: Colore
            type: colors
      gallery:
        type: fields
        fields:
          cover:
            label: Immagini nella home
            type: files
            width: 1/1
            template: image
            uploads: image
            query: page.images.filterBy('template', 'image')
            layout: cards
            size: large
            multiple: true
            max: 2
            required: true
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true
      caption:
        type: fields
        fields:
          gap:
            type: gap
            width: 1/4
          info:
            width: 1/2
            label: Didascalia
            type: writer
            marks: false
            nodes: false
  page:
    label: Pagina del progetto
    icon: page
    columns:
      sidebar:
        width: 1/2
        sections:
          media:
            type: fields
            fields:
              gallery:
                label: Immagini
                type: files
                template: image
                uploads: image
                query: page.images.filterBy('template', 'image')
                layout: cards
                size: small
                multiple: true
                image:
                  icon: true
                  ratio: 4/3
                  back: white
                  cover: true 
              video:
                label: Video
                type: files
                width: 1/1
                template: video
                uploads: video
                query: page.images.filterBy('template', 'video')
                multiple: false
                max: 1
                required: false
      main:
        width: 1/2
        sections: 
          copy:
            type: fields
            fields:
              blocks:
                label: Testi
                type: blocks                    
              pagestatus:
                label: La pagina è pronta?
                width: 1/2
                type: toggle
                text: 
                  - "no"
                  - "sì"
  subpage:
    label: Contenuto extra
    icon: star
    sections:
      info: 
        label: Info
        text: |
            I contenuti extra si aprono come elementi pop-up. Ciascun elemento è collegato a un pulsante speciale nella pagina del progetto.
            Importante: creare prima l'elemento e poi il pulsante nella pagina del progetto; il titolo del contenuto extra e del pulante devono coincidere.
      subpages:
        label: "Contenuti extra della pagina {{ page.title }}"
        type: pages
        layout: cards
        size: small
        sortable: false
        image:
          icon: true
          ratio: 4/3
          back: white
          cover: true  
        templates:
          - subpage