title: Progetto
options:
  navigation:
    status: listed
    template: project

tabs:
  projectslist:
    label: Progetto nella Home
    icon: grid-full
    sections:
      color:
        type: fields
        fields:
          color:
            width: 1/4
            label: Colore
            type: colors
      cover:
        type: fields
        fields:
          cover:
            label: Immagini nella home
            type: files
            template: image
            uploads: image
            query: page.images.filterBy('template', 'image')
            layout: cards
            size: small
            multiple: true
            max: 4
            required: true
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true   
      info:
        type: fields
        fields:
          gap:
            type: gap
            width: 1/4
          info:
            width: 1/2
            label: Didascalia
            type: writer
            marks: false
            nodes: false
            spellcheck: true
  page:
    label: Pagina del progetto
    icon: page
    columns:
      sidebar:
        width: 1/4
        sections:
          pagestatus:
            type: fields
            fields:
              pagestatus:
                label: La pagina è pronta?
                type: toggle
                text: 
                  - "no"
                  - "sì"
          media:
            type: fields
            fields:
              gallery:
                label: Immagini
                type: files
                template: image
                uploads: image
                query: page.images.filterBy('template', 'image')
                layout: list
                multiple: true
                image:
                  back: "#000"
                  icon: false
                  ratio: 6/3
                  cover: true
          buttons:
            type: fields
            fields:
              customBlocks:
                label: Pulsanti
                type: blocks
                fieldsets:
                  download:
                    name: Download File
                    icon: attachment
                    fields:
                      file:
                        label: Link del pulsante
                        type: files
                        label: File in download
                        template: document
                        uploads: document
                        info: false
                        max: 1
                      text:
                        label: Testo del pulsante
                        type: text
                        placeholder: Testo del pulsante ...
                  link:
                    name: Link
                    icon: bolt
                    fields:
                      link:
                        label: Link del pulsante
                        type: url
                      text:
                        label: Testo del pulsante
                        type: text
                        placeholder: Testo del pulsante ...
      main:
        width: 3/4
        sections: 
          copy:
            type: fields
            fields:
              maintext:
                label: Testo
                width: 1/2
                type: writer
                marks:
                  - bold
                  - italic
                  - underline
                  - link
                  - email
                nodes: false
              credits:
                label: Crediti
                width: 1/2
                type: writer
                marks:
                  - bold
                  - italic
                  - underline
                  - link
                  - email
                nodes: false