title: Flavia Zaganelli

tabs:
  website:
    label: WEBSITE
    icon: grid-full
    columns:
      main:
        width: 1/2
        sections:
          projects:
            label: Progetti
            type: pages
            layout: list
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true 
            templates:
              - project
          pages:
            label: Bio
            type: pages
            layout: list
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true 
            templates:
              - about
          footer:
            label: Footer
            type: fields
            fields:
              footer:
                width: 1/2
                type: text
                placeholder: Anno
                after: "© Flavia Zaganelli"
      calendar:
        width: 1/4
        sections:
          calendar:
            type: fields
            fields:
              calendarHeader:
                label: Calendario
                type: text
                placeholder: "What's Next"
              calendarBlocks:
                label: Lista delle date
                type: blocks
                fieldsets:
                  - text

      contact:
        width: 1/4
        sections:
          contact:
            type: fields
            fields:
              contactHeader:
                label: Contatti
                type: text
                placeholder: "Say Hi!"
              contactBlocks:
                label: Lista dei contatti
                type: blocks
                fieldsets:
                  - text
  seo:
    label: WEBSITE SEO
    icon: circle
    columns:
      main:
        width: 1/2
        sections:
          seocontent:
            type: fields
            fields:
              description:
                label: Descrizione
                type: textarea
                buttons: false
              keywords:
                label: Keywords
                type: tags         
      image:
        width: 1/4
        sections:
          image:
            type: fields
            fields:
              ogimage:
                label: Immagine di copertina
                type: files
                template: image
                uploads: image
                layout: cards
                size: huge
                multiple: false
                image:
                  back: "#000"
                  icon: false
                  ratio: 6/3
                  cover: true
      favicons:
        width: 1/4
        sections:
          favicons:
            type: fields
            fields:
              favicons:
                label: Favicons
                type: files
                template: image
                uploads: image
                layout: list
                size: small
                multiple: true


  
